"""Deterministic Markdown projections with manual-edit conflict detection."""

from __future__ import annotations

import re
import sqlite3
import unicodedata
from pathlib import Path
from typing import Any

import yaml

from .domain import canonical_json, digest_bytes, digest_text, utc_now
from .errors import error

GENERATED_MARKER = "<!-- Generated by llmwiki; edit canonical records, not this file. -->"
RENDER_RE = re.compile(r"<!-- llmwiki-render:([0-9a-f]{64}) -->")


def slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKC", value).casefold()
    chars: list[str] = []
    previous_dash = False
    for char in normalized:
        if char.isalnum():
            chars.append(char)
            previous_dash = False
        elif not previous_dash and chars:
            chars.append("-")
            previous_dash = True
    slug = "".join(chars).strip("-")
    return slug or "entity"


def page_content(entity: dict[str, Any], claims: list[dict[str, Any]]) -> tuple[str, str]:
    canonical = {
        "entity_id": entity["id"],
        "name": entity["canonical_name"],
        "slug": entity["slug"],
        "claims": claims,
    }
    canonical_digest = digest_text(canonical_json(canonical))
    frontmatter = yaml.safe_dump(
        {
            "id": entity["id"],
            "title": entity["canonical_name"],
            "slug": entity["slug"],
            "generated": True,
            "canonical_digest": canonical_digest,
        },
        allow_unicode=True,
        sort_keys=True,
    ).strip()
    lines = [
        "---",
        frontmatter,
        "---",
        "",
        GENERATED_MARKER,
        f"<!-- llmwiki-render:{canonical_digest} -->",
        "",
        f"# {entity['canonical_name']}",
        "",
    ]
    if not claims:
        lines.extend(["_No current claims selected for this projection._", ""])
    for claim in claims:
        lines.extend([f"- **{claim['status']}** — {claim['text']}"])
        for evidence in claim.get("evidence", []):
            locator = evidence["locator"]
            if locator["kind"] == "pdf":
                location = f"p. {locator['page']}, chars {locator['char_start']}–{locator['char_end']}"
            else:
                location = f"lines {locator['line_start']}–{locator['line_end']}"
            lines.append(f"  - Evidence: `{evidence['source_revision_id']}` ({location}) — “{evidence['quote']}”")
        lines.append("")
    return "\n".join(lines), canonical_digest


def render_pages(
    con: sqlite3.Connection,
    pages_dir: Path,
    *,
    include_unreviewed: bool = False,
) -> dict[str, Any]:
    pages_dir.mkdir(parents=True, exist_ok=True)
    entities = con.execute("SELECT * FROM entities ORDER BY slug, id").fetchall()
    rendered: list[str] = []
    unchanged: list[str] = []
    for entity_row in entities:
        entity = dict(entity_row)
        statuses = ("reviewed", "candidate", "disputed", "stale") if include_unreviewed else ("reviewed",)
        placeholders = ",".join("?" for _ in statuses)
        rows = con.execute(
            f"""SELECT cr.* FROM claim_revisions cr JOIN claims c ON c.id=cr.claim_id
                WHERE c.entity_id=? AND cr.is_current=1 AND cr.status IN ({placeholders})
                ORDER BY cr.created_at, cr.id""",
            (entity["id"], *statuses),
        ).fetchall()
        claims: list[dict[str, Any]] = []
        for row in rows:
            item = dict(row)
            evidence_rows = con.execute(
                "SELECT * FROM evidence WHERE claim_revision_id=? ORDER BY id", (row["id"],)
            ).fetchall()
            item["evidence"] = [
                {
                    "id": evidence["id"],
                    "source_revision_id": evidence["source_revision_id"],
                    "locator": __import__("json").loads(evidence["locator_json"]),
                    "quote": evidence["quote"],
                }
                for evidence in evidence_rows
            ]
            claims.append(item)
        content, canonical_digest = page_content(entity, claims)
        path = pages_dir / f"{entity['slug']}.md"
        try:
            rel = path.relative_to(pages_dir.parent.parent).as_posix()
        except ValueError:
            rel = path.as_posix()
        prior = con.execute("SELECT * FROM render_state WHERE page_path=?", (rel,)).fetchone()
        if prior and path.exists():
            current_file_digest = digest_bytes(path.read_bytes())
            if current_file_digest != prior["file_digest"]:
                raise error(
                    "render_conflict",
                    "Generated page has local edits; refusing to overwrite.",
                    path=str(path),
                )
        encoded = content.encode("utf-8")
        file_digest = digest_bytes(encoded)
        if path.exists() and digest_bytes(path.read_bytes()) == file_digest:
            unchanged.append(str(path))
        else:
            temporary = path.with_suffix(".md.tmp")
            temporary.write_bytes(encoded)
            temporary.replace(path)
            rendered.append(str(path))
        con.execute(
            """INSERT INTO render_state(page_path, entity_id, canonical_digest, file_digest, rendered_at)
               VALUES(?, ?, ?, ?, ?)
               ON CONFLICT(page_path) DO UPDATE SET entity_id=excluded.entity_id,
               canonical_digest=excluded.canonical_digest, file_digest=excluded.file_digest,
               rendered_at=excluded.rendered_at""",
            (rel, entity["id"], canonical_digest, file_digest, utc_now()),
        )
    return {"rendered": rendered, "unchanged": unchanged, "count": len(entities)}
