"""Page templates and wiki scaffolding."""

from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import Dict

from .model import slugify
from . import yamlio


def _today() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def new_page(title: str, type_: str = "note", status: str = "candidate") -> str:
    """Return the Markdown text of a fresh, lint-clean page."""
    slug = slugify(title)
    fm: Dict = {
        "id": f"{('entity' if type_=='entity' else 'page')}:{slug}",
        "title": title,
        "type": type_,
        "slug": slug,
        "status": status,
        "aliases": [],
        "tags": [],
        "created": _today(),
        "updated": _today(),
        "sources": [],
        "claims": [],
        "freshness": {"checked_at": _today(), "stale": False},
        "rights": {"license_expression": "", "redistribution_allowed": False},
    }
    body = (
        f"# {title}\n\n"
        "> Status: candidate — generated by an LLM, not yet reviewed.\n\n"
        "## Summary\n\n"
        "_Write a durable synthesis here. Attach each factual statement to a "
        "claim with evidence in the frontmatter._\n\n"
        "## Related\n\n"
        "_Link related pages with `[[Page Title]]` syntax (targets must exist)._\n"
    )
    return yamlio.render_page(fm, body)


WIKI_CONFIG = """\
# llmwiki configuration
name: LLM Wiki
# Directory (relative to this file) that holds rendered Markdown pages.
pages_dir: pages
# Default policy applied by the linter in --strict mode.
strict_rules:
  - missing-evidence
  - stale
"""

SAMPLE_INDEX = """\
---
id: page:index
title: Index
type: index
slug: index
status: reviewed
tags: [meta]
---

# Index

This is the wiki home page. Link out to entity and topic pages with
`[[Wikilinks]]`.
"""


def init_wiki(root: Path) -> Dict[str, str]:
    """Create the minimal wiki layout under ``root``. Returns created paths."""
    root = Path(root)
    created = {}
    pages = root / "pages"
    pages.mkdir(parents=True, exist_ok=True)
    cfg = root / "wiki.yaml"
    if not cfg.exists():
        cfg.write_text(WIKI_CONFIG, encoding="utf-8")
        created["config"] = str(cfg)
    index = pages / "index.md"
    if not index.exists():
        index.write_text(SAMPLE_INDEX, encoding="utf-8")
        created["index"] = str(index)
    return created
